export const TECH_SECTIONS = {
  FRONTEND: "FRONTEND",
  BACKEND: "BACKEND",
  NETWORKING: "NETWORKING",
  CICD: "CICD",
  FAVOURITES: "FAVOURITES",
};

export const TECH_IMAGE_PATH = "/images/tech/";
