export const TEXT_TYPE = {
  HEADER: "HEADER",
  TEXT: "TEXT",
};

export const CHAR_ANIMATIONS = {
  FLASH_IN: "FLASH_IN",
  FADE_IN_LEFT: "FADE_IN_LEFT",
  MULTI_FLASH: "MULTI_FLASH",
  TEST: "TEST",
  FADE_UP: "FADE_UP",
};
